<div class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a href="http://190.41.246.91/web/index.php" class="brand"><img class="icr-img" src="http://190.41.246.91/web/resource/icrlogo.png"></a>
			<a class="brand" href="http://190.41.246.91/web/web-almacen/home.php">Modulo Ventas</a>
			<div class="nav-collapse in">
				<ul class="nav" role="navigation">
					<li class="active">
						<a href="http://190.41.246.91/web/web-ventas/index.php"><i class="icon-home"></i>
						</a>
					</li>					
				</ul>
			</div>
		</div>
	</div>
</div>