<hgroup>
	<ul id="menu">
		<li><a href="http://190.41.246.91/web-cotiza/intranet/index.php">Inicio</a></li>
		<li>
			<a href="">Cotización</a>
			<ul>
				<li><a href="http://190.41.246.91/web-cotiza/intranet/cotizacion.php">Cotizar</a></li>
				<li><a href="http://190.41.246.91/web-cotiza/intranet/cotcalc.php">Cotizar con Excel</a></li>
				<li><a href="http://190.41.246.91/web-cotiza/intranet/viewkey.php">Ver Keygens</a></li>
				<li><a href="http://190.41.246.91/web-cotiza/intranet/compararcot.php">Comparar Cotizacion</a></li>
				<li><a href="http://190.41.246.91/web-cotiza/intranet/estadocotizacion.php">Estado Cotizacion</a></li>
				<li><a href="http://190.41.246.91/web-cotiza/intranet/estadocompra.php">Estado Compras</a></li>
			</ul>
		</li>
		<li>
			<a href="">Mantenimientos</a>
			<ul>
				<li><a href="http://190.41.246.91/web-cotiza/intranet/proyectos.php">Proyectos</a></li>
				<li><a href="http://190.41.246.91/web-cotiza/intranet/clientes.php">Clientes</a></li>
				<li><a href="http://190.41.246.91/web-cotiza/intranet/moneda.php">Monedas</a></li>
				<li><a href="http://190.41.246.91/web-cotiza/intranet/proveedor.php">Proveedores</a></li>
				<li><a href="http://190.41.246.91/web-cotiza/intranet/estados.php">Estados</a></li>
				<li><a href="">Logins</a>
					<ul>
						<li><a href="http://190.41.246.91/web-cotiza/intranet/login-pro.php">Login Proveedor</a></li>
						<li><a href="http://190.41.246.91/web-cotiza/intranet/login-per.php">Login Personal</a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li>
		<a href="">Reportes</a>
		<ul>
			<li><a href="http://190.41.246.91/web-cotiza/intranet/report/rptcotizacion.php">Cotización</a></li>
			<li><a href="http://190.41.246.91/web-cotiza/intranet/report/rptcompra.php">Orden Compra</a></li>
		</ul>
		</li>
		<li><a href="about.php">About</a></li>
		<li><a href="#">Contacto</a></li>
	</ul>
</hgroup>
